// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOv5fRRa2NT_D1cEfH0b0sQRPoYdPrxVE',
    appId: '1:642221219894:web:1692aef3f0b4a88afbf897',
    messagingSenderId: '642221219894',
    projectId: 'notesify-flutter-project',
    authDomain: 'notesify-flutter-project.firebaseapp.com',
    storageBucket: 'notesify-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdBvAzjc-KTE0N-7_3MrnN20Vv-16Ceno',
    appId: '1:642221219894:android:dd3384c94d03893ffbf897',
    messagingSenderId: '642221219894',
    projectId: 'notesify-flutter-project',
    storageBucket: 'notesify-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7-dOwKLA2mF3ZFlHmNvc5Fp8XnJzdWPo',
    appId: '1:642221219894:ios:e6cb98cbf4fb27c9fbf897',
    messagingSenderId: '642221219894',
    projectId: 'notesify-flutter-project',
    storageBucket: 'notesify-flutter-project.appspot.com',
    iosClientId: '642221219894-v8q9trjnfjmav3792unefam0tm7gs2ks.apps.googleusercontent.com',
    iosBundleId: 'np.aayyyyyushcodes.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7-dOwKLA2mF3ZFlHmNvc5Fp8XnJzdWPo',
    appId: '1:642221219894:ios:e6cb98cbf4fb27c9fbf897',
    messagingSenderId: '642221219894',
    projectId: 'notesify-flutter-project',
    storageBucket: 'notesify-flutter-project.appspot.com',
    iosClientId: '642221219894-v8q9trjnfjmav3792unefam0tm7gs2ks.apps.googleusercontent.com',
    iosBundleId: 'np.aayyyyyushcodes.mynotes',
  );
}
